---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  db_host: mongodb-service

---
apiVersion: v1
kind: secret
metadata:
  name: Mongodb-secret
type: opaque
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=

---
apiVersion: v1
kind: secret
metadata:
  name: mongoexpress-secret
type: opaque
data:
  mduser: YWRtaW4=
  mdpass: YWRtaW4xMjM=
  meuser: YWRtaW4=
  mepass: YWRtaW4xMjM=

---
apiVersion: v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchlabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: Mongodb-secret
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: Mongodb-secret
                  key: password
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc

---

