apiVersion: v1
kind: PersistentVolume 
metadata: 
   name: mongo-data 
spec: 
   capacity:
      storage: 1Gi  # storage size
   accessModes:
     - ReadWriteOnce # Access mode: can only be mounted by a single node at a time
   persistentVolumeReclaimPolicy: Retain 
   storageClassName: standard
   hostPath:
      path: /home/cloud_user/mongo/mongo-vol  # create the path before creating the PV.
  
