apiVersion: v1
kind: Pod
metadata: 
   name: firstpod
   labels:
      app: httpd_app
spec:
   containers:
        - name: httpd-container
          image: httpd:latest
          ports:
            - containerPort: 8080 
